//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int MobileNumber { get; set; }
        public string Address { get; set; }
        public string SkillLevel { get; set; }
        public int Salary { get; set; }
        public string Email { get; set; }
        public Nullable<int> Hirer_Id { get; set; }
        public int Experience { get; set; }
        public string Domains { get; set; }
        public string Technologies { get; set; }
        public Nullable<int> Domain_Id { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual Hirer Hirer { get; set; }
    }
}
